ViewModels/LayoutViewModels.cs
using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SimpleBlog.ViewModels
{
    public class SidebarTag
    {
        public int Id { get; private set; }
        public string Name { get; private set; }
        public string Slug { get; private set; }
        public int PostCount { get; private set; }

        public SidebarTag(int id, string name, string slug, int postCount)
        {
            Id = id;
            Name = name;
            Slug = slug;
            PostCount = postCount;
        }
    }
    public class LayoutSidebar
    {
        public bool IsLoggedIn { get; set; }
        public string Username { get; set; }
        public bool IsAdminRole { get; set; }
        public IEnumerable<SidebarTag> Tags { get; set; }
    }
}

Controllers/LayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NHibernate.Linq;
using SimpleBlog.Infrastructure.Authentication;
using SimpleBlog.NHibernate;
using SimpleBlog.NHibernate.Entities;
using SimpleBlog.ViewModels;

namespace SimpleBlog.Controllers
{
    public class LayoutController : Controller
    {
        [ChildActionOnly]
        public ActionResult Sidebar()
        {
            return View(new LayoutSidebar
            {
                IsLoggedIn =  SiteAuthManager.CurrentUser != null,
                Username = SiteAuthManager.CurrentUser != null ? SiteAuthManager.CurrentUser.Username : "",
                IsAdminRole = User.IsInRole("Admin"),
                Tags = Database.Session.Query<Tag>()
                .Select(tag => new
                {
                    tag.Id,
                    tag.Name,
                    tag.Slug,
                    PostCount = tag.Posts.Count
                })
                .Where(t => t.PostCount > 0)
                .OrderByDescending(p => p.PostCount)
                .Select(tag => new SidebarTag (tag.Id, tag.Name, tag.Slug, tag.PostCount))
                .ToList()
            });
        }
    }
}

Views/Shared/_Layout.cshtml
@using System.Web.Optimization

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title> @ViewBag.Title - My ASP.NET Application </title>
    @Styles.Render("~/Frontend/Styles")
</head>
<body>
    <div class="site-header">
        <header class="container">
            <h1 class="page-header">
                <a href="@Url.RouteUrl("Home")">Awesome Stuff!</a>
                <small>a simple blog powered by APS.net MVC</small>
            </h1>
        </header>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                @RenderBody()
            </div>
            <div class="col-lg-4 sidebar">
                @Html.Action("Sidebar", "Layout")
            </div>
        </div>

        <footer>
            &copy; @DateTime.UtcNow.Year
        </footer>
    </div>

    @Scripts.Render("~/Frontend/Scripts")
    @RenderSection("Scripts", required: false)
</body>
</html>